kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: golang:1.17
    commands:
      - go build -v ./...
  - name: test
    image: golang:1.17
    commands:
      - go test -cover -covermode=atomic -coverprofile=coverage.out -race -v ./...
      - go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'
  - name: outfile
    image: golang:1.17
    commands:
      - echo hello > hello.txt
