name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: build
        run: go build -v ./...

      - name: test
        run: go test -cover -covermode=atomic -coverprofile=coverage.out -race -v ./...

      - name: publish code cov
        uses: actions/upload-artifact@v2
        with:
          name: code coverage report
          path: coverage.out

      - name: Add Coverage Label
        uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.setLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['COV: 37.5']
            })

      - name: Publish cod cov badge
        run: |
          set -x
          total=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`

          if (( $(echo "$total <= 50" | bc -l) )) ; then
            COLOR=red
          elif (( $(echo "$total > 80" | bc -l) )); then
            COLOR=green
          else
            COLOR=orange
          fi

          curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > coverage.svg
